// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZbW.ITB1821H.OrderManager.Model.Context;

namespace ZbW.ITB1821H.OrderManager.Model.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210906201404_ChangeCteFromSPtoTVF")]
    partial class ChangeCteFromSPtoTVF
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            City = "Mankato",
                            Country = "US",
                            PostalCode = "96522",
                            State = "MS",
                            Street = "711 Nulla St."
                        },
                        new
                        {
                            Id = 1001,
                            City = "Richardson",
                            Country = "US",
                            PostalCode = "75080",
                            State = "TX",
                            Street = "994 North Del Monte Ave."
                        },
                        new
                        {
                            Id = 1002,
                            City = "Ottawa",
                            Country = "US",
                            PostalCode = "61350",
                            State = "IL",
                            Street = "4 Arnold Ave."
                        },
                        new
                        {
                            Id = 1003,
                            City = "Pataskala",
                            Country = "US",
                            PostalCode = "43062",
                            State = "OH",
                            Street = "7376 NE. Woodman Drive"
                        },
                        new
                        {
                            Id = 1004,
                            City = "Milton",
                            Country = "US",
                            PostalCode = "02186",
                            State = "MA",
                            Street = "821 Hanover St."
                        },
                        new
                        {
                            Id = 1005,
                            City = "Mcdonough",
                            Country = "US",
                            PostalCode = "30252",
                            State = "GA",
                            Street = "279 University St."
                        },
                        new
                        {
                            Id = 1006,
                            City = "Torrington",
                            Country = "US",
                            PostalCode = "06790",
                            State = "CT",
                            Street = "8484 High Street"
                        },
                        new
                        {
                            Id = 1008,
                            City = "Riverside",
                            Country = "US",
                            PostalCode = "08075",
                            State = "NJ",
                            Street = "334 Pineknoll Court"
                        },
                        new
                        {
                            Id = 1009,
                            City = "Ocean Springs",
                            Country = "US",
                            PostalCode = "39564",
                            State = "MS",
                            Street = "153 Wood St."
                        },
                        new
                        {
                            Id = 1010,
                            City = "Elgin",
                            Country = "US",
                            PostalCode = "60120",
                            State = "IL",
                            Street = "151 Thorne Drive"
                        },
                        new
                        {
                            Id = 1011,
                            City = "West Islip",
                            Country = "US",
                            PostalCode = "11795",
                            State = "NY",
                            Street = "21 Lawrence Lane"
                        },
                        new
                        {
                            Id = 1012,
                            City = "Long Beach",
                            Country = "US",
                            PostalCode = "39564",
                            State = "NY",
                            Street = "514 Hill Drive"
                        },
                        new
                        {
                            Id = 1013,
                            City = "Westport",
                            Country = "US",
                            PostalCode = "06880",
                            State = "CT",
                            Street = "2 S. Manhattan St."
                        },
                        new
                        {
                            Id = 1014,
                            City = "Thornton",
                            Country = "US",
                            PostalCode = "80241",
                            State = "CO",
                            Street = "439 San Pablo Street"
                        },
                        new
                        {
                            Id = 1015,
                            City = "Lexington",
                            Country = "US",
                            PostalCode = "27292",
                            State = "NC",
                            Street = "873 Alderwood Ave."
                        },
                        new
                        {
                            Id = 1016,
                            City = "Westwood",
                            Country = "US",
                            PostalCode = "07675",
                            State = "NJ",
                            Street = "7746 Pulaski Lane"
                        },
                        new
                        {
                            Id = 1017,
                            City = "Teaneck",
                            Country = "US",
                            PostalCode = "07666",
                            State = "NJ",
                            Street = "77 Pearl Street"
                        },
                        new
                        {
                            Id = 1018,
                            City = "Stockbridge",
                            Country = "US",
                            PostalCode = "30281",
                            State = "GA ",
                            Street = "550 Locust Court"
                        },
                        new
                        {
                            Id = 1019,
                            City = "Virginia Beach",
                            Country = "US",
                            PostalCode = "23451",
                            State = "VA",
                            Street = "19 Paris Hill Circle"
                        },
                        new
                        {
                            Id = 1020,
                            City = "West Deptford",
                            Country = "US",
                            PostalCode = "08096",
                            State = "NJ",
                            Street = "508 Manhattan Street"
                        },
                        new
                        {
                            Id = 1021,
                            City = "Tallahassee",
                            Country = "US",
                            PostalCode = "32303",
                            State = "FL",
                            Street = "19 Shirley Dr."
                        });
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ArticleGroupId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            ArticleGroupId = 11,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh from Switzerland",
                            IsActive = false,
                            Name = "Apple",
                            Price = 0.94999999999999996
                        },
                        new
                        {
                            Id = 101,
                            ArticleGroupId = 11,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh from Columbia",
                            IsActive = false,
                            Name = "Banana",
                            Price = 1.1200000000000001
                        },
                        new
                        {
                            Id = 102,
                            ArticleGroupId = 12,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Swiss Quality",
                            IsActive = false,
                            Name = "Chicken",
                            Price = 2.0299999999999998
                        },
                        new
                        {
                            Id = 103,
                            ArticleGroupId = 12,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Atlantic Ocean",
                            IsActive = false,
                            Name = "Salmon",
                            Price = 1.5600000000000001
                        },
                        new
                        {
                            Id = 104,
                            ArticleGroupId = 13,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Switzerland",
                            IsActive = false,
                            Name = "Cheese",
                            Price = 2.2200000000000002
                        },
                        new
                        {
                            Id = 105,
                            ArticleGroupId = 13,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Based on years of experience",
                            IsActive = false,
                            Name = "Yogurt",
                            Price = 2.3399999999999999
                        });
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.ArticleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("ArticleGroups");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Description = "all food",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Worldwide selection of Fruits",
                            Name = "Fruits",
                            ParentGroupId = 10
                        },
                        new
                        {
                            Id = 12,
                            Description = "Good Quality Meat",
                            Name = "Meat",
                            ParentGroupId = 10
                        },
                        new
                        {
                            Id = 13,
                            Description = "Milk for everyone!",
                            Name = "Dairy",
                            ParentGroupId = 10
                        });
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1000,
                            Email = "cecilia@chapman.com",
                            LastName = "Chapman",
                            Name = "Cecilia",
                            PasswordHash = "E14CE3435BC3194B77C609F26EF6075E",
                            PasswordSalt = "12837163",
                            Website = "https://chapman.com"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 1001,
                            Email = "iris-watson@gmail.com",
                            LastName = "Watson",
                            Name = "Iris",
                            PasswordHash = "73A3E02C4DD27B55E06022C50D7D0AFC",
                            PasswordSalt = "78920238",
                            Website = "www.facebook.com/asdf"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 1002,
                            Email = "c3l3steee_Slater@yahoo.com",
                            LastName = "Slater",
                            Name = "Celeste",
                            PasswordHash = "D363DA161F0435AFA33522ECE8CF9028",
                            PasswordSalt = "79543238",
                            Website = "www.facebook.com"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 1003,
                            Email = "theo.Lowe@bdd_dd.com",
                            LastName = "Lowe",
                            Name = "Theodore",
                            PasswordHash = "236ED504E07B07B0A5A258267A076280",
                            PasswordSalt = "09820278",
                            Website = "http://lowe.net"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 1004,
                            Email = "asdf@1234.info",
                            LastName = "Wise",
                            Name = "Calista",
                            PasswordHash = "63DFD2DAC00052149A13AD90D46E72F4",
                            PasswordSalt = "02649823",
                            Website = "wise.de"
                        },
                        new
                        {
                            Id = 6,
                            AddressId = 1005,
                            Email = "kyla.o_sen@outlook.com",
                            LastName = "Olsen",
                            Name = "Kyla",
                            PasswordHash = "A4AD9F5525A4A438A30D9BA6F439EE11",
                            PasswordSalt = "48219463",
                            Website = "https://olsen.com"
                        },
                        new
                        {
                            Id = 7,
                            AddressId = 1014,
                            Email = "ray-forrester@gmail.com",
                            LastName = "Forrester",
                            Name = "Ray",
                            PasswordHash = "0D165FB2F6A4BDC58AA47F27A61D7CC3",
                            PasswordSalt = "34298733",
                            Website = "https://www.forrester.com"
                        },
                        new
                        {
                            Id = 8,
                            AddressId = 1006,
                            Email = "lawrence.vazquez@outlook.com",
                            LastName = "Vazquez",
                            Name = "Lawrence",
                            PasswordHash = "0615B09A41716D1D0B82AFE7776DAA63",
                            PasswordSalt = "92736482",
                            Website = "www.youtube.com"
                        },
                        new
                        {
                            Id = 9,
                            AddressId = 1015,
                            Email = "hawkins@ab_cd.net",
                            LastName = "Hawkins",
                            Name = "Aaron",
                            PasswordHash = "24C5B4576280B8758727185655D4AF01",
                            PasswordSalt = "09374832",
                            Website = "google.com"
                        },
                        new
                        {
                            Id = 10,
                            AddressId = 1008,
                            Email = "melvin@gmail.com",
                            LastName = "Porter",
                            Name = "Melvin",
                            PasswordHash = "D5C3FCDDA77E375170260A70ADF46185",
                            PasswordSalt = "26374819",
                            Website = "https://www.google.com"
                        },
                        new
                        {
                            Id = 11,
                            AddressId = 1009,
                            Email = "colbyyyy@gmail.com",
                            LastName = "Colby",
                            Name = "Bernard",
                            PasswordHash = "60EDAF581460E45293444C173AEC4445",
                            PasswordSalt = "16370362",
                            Website = "https://policies.google.com/technologies/voice?hl=de&gl=ch"
                        },
                        new
                        {
                            Id = 12,
                            AddressId = 1010,
                            Email = "russell--adria@outlook.com",
                            LastName = "Adria",
                            Name = "Russell",
                            PasswordHash = "786BD8C931054AE53B10575711F3A6BD",
                            PasswordSalt = "98873662",
                            Website = "russell.com"
                        },
                        new
                        {
                            Id = 13,
                            AddressId = 1011,
                            Email = "chester@bennett.com",
                            LastName = "Bennett",
                            Name = "Chester",
                            PasswordHash = "65BAD922A870FBFC45A98B4C223B989E",
                            PasswordSalt = "47823891",
                            Website = "www.facebook.com"
                        },
                        new
                        {
                            Id = 14,
                            AddressId = 1012,
                            Email = "harr.mcg@outlook.com",
                            LastName = "Mcguire",
                            Name = "Harrison",
                            PasswordHash = "1ADB43FEDBAB65E3B46170C41A21076A",
                            PasswordSalt = "67541952",
                            Website = "outlook.ch"
                        },
                        new
                        {
                            Id = 15,
                            AddressId = 1013,
                            Email = "wallace@rosss.com",
                            LastName = "Ross",
                            Name = "Wallace",
                            PasswordHash = "D797C7C0C03EAC0CCF9AC8D2E826ED5C",
                            PasswordSalt = "12340534",
                            Website = "rosss.com"
                        });
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1234,
                            CustomerId = 1,
                            DateOfPurchase = new DateTime(2021, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1235,
                            CustomerId = 2,
                            DateOfPurchase = new DateTime(2021, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1236,
                            CustomerId = 2,
                            DateOfPurchase = new DateTime(2021, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1237,
                            CustomerId = 2,
                            DateOfPurchase = new DateTime(2021, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1238,
                            CustomerId = 3,
                            DateOfPurchase = new DateTime(2021, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1239,
                            CustomerId = 3,
                            DateOfPurchase = new DateTime(2021, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1230,
                            CustomerId = 4,
                            DateOfPurchase = new DateTime(2021, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1240,
                            CustomerId = 4,
                            DateOfPurchase = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1231,
                            CustomerId = 6,
                            DateOfPurchase = new DateTime(2021, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1232,
                            CustomerId = 7,
                            DateOfPurchase = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1233,
                            CustomerId = 8,
                            DateOfPurchase = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1241,
                            CustomerId = 8,
                            DateOfPurchase = new DateTime(2020, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1242,
                            CustomerId = 10,
                            DateOfPurchase = new DateTime(2020, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1243,
                            CustomerId = 11,
                            DateOfPurchase = new DateTime(2021, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1244,
                            CustomerId = 11,
                            DateOfPurchase = new DateTime(2021, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1245,
                            CustomerId = 11,
                            DateOfPurchase = new DateTime(2021, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1246,
                            CustomerId = 14,
                            DateOfPurchase = new DateTime(2021, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1247,
                            CustomerId = 15,
                            DateOfPurchase = new DateTime(2021, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1248,
                            CustomerId = 15,
                            DateOfPurchase = new DateTime(2021, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PosNr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("OrderId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 23,
                            ArticleId = 100,
                            OrderId = 1230,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 30,
                            ArticleId = 101,
                            OrderId = 1230,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 12,
                            ArticleId = 102,
                            OrderId = 1230,
                            PosNr = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 34,
                            ArticleId = 103,
                            OrderId = 1230,
                            PosNr = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100,
                            ArticleId = 100,
                            OrderId = 1231,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 200,
                            ArticleId = 102,
                            OrderId = 1231,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 55,
                            ArticleId = 104,
                            OrderId = 1232,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 35,
                            ArticleId = 105,
                            OrderId = 1232,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 9,
                            Amount = 20,
                            ArticleId = 100,
                            OrderId = 1232,
                            PosNr = 3
                        },
                        new
                        {
                            Id = 10,
                            Amount = 10,
                            ArticleId = 101,
                            OrderId = 1232,
                            PosNr = 4
                        },
                        new
                        {
                            Id = 11,
                            Amount = 5,
                            ArticleId = 102,
                            OrderId = 1232,
                            PosNr = 5
                        },
                        new
                        {
                            Id = 12,
                            Amount = 50,
                            ArticleId = 103,
                            OrderId = 1232,
                            PosNr = 6
                        },
                        new
                        {
                            Id = 13,
                            Amount = 86,
                            ArticleId = 100,
                            OrderId = 1233,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 14,
                            Amount = 134,
                            ArticleId = 101,
                            OrderId = 1233,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 15,
                            Amount = 100,
                            ArticleId = 102,
                            OrderId = 1233,
                            PosNr = 3
                        },
                        new
                        {
                            Id = 16,
                            Amount = 90,
                            ArticleId = 103,
                            OrderId = 1233,
                            PosNr = 4
                        },
                        new
                        {
                            Id = 17,
                            Amount = 134,
                            ArticleId = 103,
                            OrderId = 1234,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 18,
                            Amount = 56,
                            ArticleId = 104,
                            OrderId = 1234,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 65,
                            ArticleId = 105,
                            OrderId = 1234,
                            PosNr = 3
                        },
                        new
                        {
                            Id = 20,
                            Amount = 73,
                            ArticleId = 103,
                            OrderId = 1235,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 21,
                            Amount = 77,
                            ArticleId = 105,
                            OrderId = 1235,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 22,
                            Amount = 98,
                            ArticleId = 105,
                            OrderId = 1236,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 23,
                            Amount = 123,
                            ArticleId = 104,
                            OrderId = 1236,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 24,
                            Amount = 451,
                            ArticleId = 103,
                            OrderId = 1237,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 25,
                            Amount = 345,
                            ArticleId = 102,
                            OrderId = 1237,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 26,
                            Amount = 557,
                            ArticleId = 100,
                            OrderId = 1238,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 27,
                            Amount = 45,
                            ArticleId = 101,
                            OrderId = 1238,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 28,
                            Amount = 256,
                            ArticleId = 102,
                            OrderId = 1238,
                            PosNr = 3
                        },
                        new
                        {
                            Id = 29,
                            Amount = 234,
                            ArticleId = 103,
                            OrderId = 1238,
                            PosNr = 4
                        },
                        new
                        {
                            Id = 30,
                            Amount = 56,
                            ArticleId = 104,
                            OrderId = 1238,
                            PosNr = 5
                        },
                        new
                        {
                            Id = 31,
                            Amount = 134,
                            ArticleId = 105,
                            OrderId = 1238,
                            PosNr = 6
                        },
                        new
                        {
                            Id = 32,
                            Amount = 567,
                            ArticleId = 104,
                            OrderId = 1239,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 33,
                            Amount = 87,
                            ArticleId = 105,
                            OrderId = 1239,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 34,
                            Amount = 47,
                            ArticleId = 101,
                            OrderId = 1240,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 35,
                            Amount = 83,
                            ArticleId = 102,
                            OrderId = 1241,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 36,
                            Amount = 95,
                            ArticleId = 103,
                            OrderId = 1241,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 37,
                            Amount = 75,
                            ArticleId = 104,
                            OrderId = 1242,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 38,
                            Amount = 45,
                            ArticleId = 105,
                            OrderId = 1242,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 39,
                            Amount = 75,
                            ArticleId = 100,
                            OrderId = 1242,
                            PosNr = 3
                        },
                        new
                        {
                            Id = 40,
                            Amount = 25,
                            ArticleId = 102,
                            OrderId = 1243,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 41,
                            Amount = 35,
                            ArticleId = 103,
                            OrderId = 1243,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 42,
                            Amount = 51,
                            ArticleId = 105,
                            OrderId = 1244,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 43,
                            Amount = 15,
                            ArticleId = 103,
                            OrderId = 1245,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 44,
                            Amount = 36,
                            ArticleId = 104,
                            OrderId = 1245,
                            PosNr = 2
                        },
                        new
                        {
                            Id = 45,
                            Amount = 99,
                            ArticleId = 105,
                            OrderId = 1245,
                            PosNr = 3
                        },
                        new
                        {
                            Id = 46,
                            Amount = 100,
                            ArticleId = 100,
                            OrderId = 1246,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 47,
                            Amount = 35,
                            ArticleId = 101,
                            OrderId = 1247,
                            PosNr = 1
                        },
                        new
                        {
                            Id = 48,
                            Amount = 75,
                            ArticleId = 102,
                            OrderId = 1248,
                            PosNr = 1
                        });
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Article", b =>
                {
                    b.HasOne("ZbW.ITB1821H.OrderManager.Model.Entities.ArticleGroup", "ArticleGroup")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleGroup");
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.ArticleGroup", b =>
                {
                    b.HasOne("ZbW.ITB1821H.OrderManager.Model.Entities.ArticleGroup", "ParentGroup")
                        .WithMany("SubArticleGroups")
                        .HasForeignKey("ParentGroupId");

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Customer", b =>
                {
                    b.HasOne("ZbW.ITB1821H.OrderManager.Model.Entities.Address", "Address")
                        .WithMany("Customers")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Order", b =>
                {
                    b.HasOne("ZbW.ITB1821H.OrderManager.Model.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Position", b =>
                {
                    b.HasOne("ZbW.ITB1821H.OrderManager.Model.Entities.Article", "Article")
                        .WithMany("Positions")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZbW.ITB1821H.OrderManager.Model.Entities.Order", "Order")
                        .WithMany("Positions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Address", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Article", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.ArticleGroup", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("SubArticleGroups");
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ZbW.ITB1821H.OrderManager.Model.Entities.Order", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
